### PR TITLE
Fix/add locale option

### LINKED ISSUE #39: Use the Locale on date-fns functions
## Issue 

#38 is a good demonstration for this bug. If I change `locale` to the one that has **Monday as their first day of the week**, the calendar will not respect that. Eg. Italian `locale` https://github.com/date-fns/date-fns/blob/v2.25.0/src/locale/it/index.js

JPEG-1

Has an `options.weekStartsOn = 1`. With #38, it gives:

JPEG-2

Where **Dom** (domenica) is Sunday in Italian and **Lun** (lunedì) is Monday in Italina

## Solution

Whenever date-fns functions are used, they should given the `locale` object.
https://date-fns.org/v2.28.0/docs/Locale

I will see if I could submit a PR for this. Thank you

### PR DESCRIPTION
**Pull request by tomchentw**
Closes #39 .

## Notes

Good day, @uselessdev. Not until I tried to address #39 did I realize that the interfaces already have the `weekStartsOn` option. This PR adds the `locale` to the date-fn options along with some existing `weekStartsOn` option. I'm not sure if you like this approach though so please feel free to ditch this PR.

Although `date-fns` also supports specifying `locale` and `weekStartsOn` in the options in the same time, I personally prefer keeping only the `locale` option in the interface for simplicity. But this involves a breaking change so let's discuss it first.

### Pros

- Simplicity
- Less cognitive overload
- Align with date-fns

### Cons

- Breaking changes
- Unable to customize if we don't want to pull in a locale object

### CODE REVIEW

File: src/calendar.tsx [hunk 1]
```diff
@@ -74,7 +75,10 @@ export function Calendar({
     }
 
     if (weekDateSelection) {
-      return onSelectDate({ start: startOfWeek(date), end: endOfWeek(date) })
+      return onSelectDate({
+        start: startOfWeek(date, { locale }),
```
Comment (tomchentw) [inline src/calendar.tsx:79]: Do we also need to add `weekStartsOn` to the option here?

File: src/calendar.tsx [hunk 2]
```diff
@@ -74,7 +75,10 @@ export function Calendar({
...
+        end: endOfWeek(date, { locale }),
```
Comment (tomchentw) [inline src/calendar.tsx:80]: and here

File: src/useCalendar.ts [hunk 3]
```diff
@@ -28,6 +30,7 @@ export function useCalendar({
   months = 1,
   blockFuture,
   allowOutsideDays,
+  locale,
   weekStartsOn = 0,
```
Comment (uselessdev) [inline src/useCalendar.ts:34]: we can remove the default value here, this will override the `locale.options.weekStartsOn`

File: src/calendar.tsx (hunk 1 above)
Comment (uselessdev) [reply src/calendar.tsx:79]: yup, we'll need this for week's selection:

If we change the locale for `it` and the start of the week to Sunday and try to use the week selection, the start value will be monday (this is weird)

image

File: src/month-days.tsx [hunk 4]
```diff
@@ -95,7 +96,7 @@ export function CalendarDays() {
           <Day
             variant={variant}
             day={day}
-            key={format(day, 'd-M')}
+            key={format(day, 'd-M', { locale })}
```
Comment (uselessdev) [inline src/month-days.tsx:99]: **question**: do we need to add the locale here?

**Review by uselessdev — CHANGES_REQUESTED** [review]

**Comment by uselessdev** [comment]
@tomchentw thanks again.

About the `locale` and `weekStartsOn` props I think we can keep the both options for now.

File: src/month-days.tsx (hunk 4 above)
Comment (tomchentw) [reply src/month-days.tsx:99]: @uselessdev since it's used for only React key here, it seems unnecessary to pass in the `locale` object. I'll revert this

**Comment by tomchentw** [comment]
@uselessdev I've updated the PR. Please review.

If it's not too much trouble, would you mind cutting a release after merging this?

Thank you 🙏

**Review by uselessdev — APPROVED** [review]

**Comment by uselessdev** [comment]
> If it's not too much trouble, would you mind cutting a release after merging this?

Yes, I'll make a new release 😊

**Comment by tomchentw** [comment]
Thank you! `2.4.0` seems to work perfectly as expected. 😄
